"""org table update

Revision ID: c7daa54b0fd5
Revises: e7f220be4500
Create Date: 2026-05-02 17:11:44.752481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7daa54b0fd5'
down_revision: Union[str, Sequence[str], None] = 'e7f220be4500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'email')
    # ### end Alembic commands ###
